<?xml version='1.0'?>
<robot name="AR2A" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisGround" value="0.13"/>
  <xacro:property name="chassisHeight" value="0.2"/>  
  <xacro:property name="chassisLength" value="0.45"/>  
  <xacro:property name="chassisWidth" value="0.25"/>
  <xacro:property name="chassisMass" value="6"/>  
  
  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.05"/>  
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="5"/>
  
  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.5"/>
  <xacro:property name="cameraPosX" value="0.1"/>
  <xacro:property name="cameraPosY" value="0.0"/>
  <xacro:property name="cameraPosZ" value="0.14"/>
    
  <xacro:include filename="$(find ar2a_description)/urdf/ar2a.gazebo" />
  <xacro:include filename="$(find ar2a_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find ar2a_description)/urdf/macros.xacro" />
  <xacro:include filename="$(find ar2a_description)/urdf/kinect.xacro" />
  
  <link name="footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>
  
  <link name='chassis'>
    
    <collision> 
      <origin xyz="0 0 ${chassisGround}" rpy="0 0 0"/> 
      <geometry> 
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
      </geometry> 
    </collision>
    
    <visual> 
      <origin xyz="0 0 ${chassisGround}" rpy="0 0 0"/> 
      <geometry> 
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
      </geometry> 
      <material name="orange"/>
    </visual>
    
    <inertial> 
      <origin xyz="0 0 ${chassisGround}" rpy="0 0 0"/> 
      <mass value="${chassisMass}"/> 
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>
  
  <wheel lr="left_front" x_pos="${wheelPos}" y_pos="${wheelWidth/2+chassisWidth/2}"/>
  <wheel lr="left_middle" x_pos="0.0" y_pos="${wheelWidth/2+chassisWidth/2}"/>
  <wheel lr="left_back" x_pos="${-wheelPos}" y_pos="${wheelWidth/2+chassisWidth/2}"/>
  <wheel lr="right_front" x_pos="${wheelPos}" y_pos="${-wheelWidth/2-chassisWidth/2}"/>
  <wheel lr="right_middle" x_pos="0.0" y_pos="${-wheelWidth/2-chassisWidth/2}"/>
  <wheel lr="right_back" x_pos="${-wheelPos}" y_pos="${-wheelWidth/2-chassisWidth/2}"/>
      
  <kinect_camera/>

</robot>
